#!/bin/bash

# 5.3.1 - Ensure password creation requirements are configured

#  The pam_pwquality.so module checks the strength of passwords. It performs checks such
#  as making sure a password is not a dictionary word, it is a certain length, contains a mix of
#  characters (e.g. alphabet, numeric, other) and more. The following are definitions of the
#  pam_pwquality .so options.
#  - try_first_pass - retrieve the password from a previous stacked PAM module. If not available, then prompt the user for a password.
#  - retry=3 - Allow 3 tries before sending back a failure.

#  The following options are set in the /etc/security/pwquality.conf file:
#  - minlen = 14 - password must be 14 characters or more
#  - dcredit = -1 - provide at least one digit
#  - ucredit = -1 - provide at least one uppercase character
#  - ocredit = -1 - provide at least one special character
#  - lcredit = -1 - provide at least one lowercase character
#  The settings shown above are one possible policy. Alter these values to conform to your
#  own organization's password policies.

test=$1

# check for Augtool
type augtool &> /dev/null

if [[ $? == 1 ]]
then
    echo -e "\n>>> Augtool binary not installed on this host, skipping this rule..."
    exit 1
fi


ret=$(augtool print "/files/etc/pam.d/password-auth/*[module='pam_pwquality.so'][type='password'][control='requisite']/argument[ . = 'try_first_pass']")
if [[ -z "${ret}" ]]
then
    echo -e "\n>>> try_first_pass is not set in /etc/pam.d/password-auth"

    if [[ -z $test ]]
    then
        echo -e "\n>>> Setting try_first_pass in /etc/pam.d/password-auth.."
        augtool set "/files/etc/pam.d/password-auth/*[module='pam_pwquality.so'][type='password'][control='requisite']/argument[ . = 'try_first_pass'] try_first_pass"
    fi
fi

ret=$(augtool print "/files/etc/pam.d/password-auth/*[module='pam_pwquality.so'][type='password'][control='requisite']/argument[ . =~ regexp(\"retry=3\")]")
if [[ -z "${ret}" ]]
then
    echo -e "\n>>> retry=3 is not set in /etc/pam.d/password-auth"

    if [[ -z $test ]]
    then
        echo -e "\n>>> Setting retry=3 in /etc/pam.d/password-auth.."
        augtool set "/files/etc/pam.d/password-auth/*[module='pam_pwquality.so'][type='password'][control='requisite']/argument[ . =~ regexp(\"retry=.*\")] retry=3"
    fi
fi
