#!/bin/bash

# 5.6 Ensure access to the su command is restricted

# Description:
# The su command allows a user to run a command or shell as another user. The program
# has been superseded by sudo , which allows for more granular control over privileged
# access. Normally, the su command can be executed by any user. By uncommenting the
# pam_wheel.so statement in /etc/pam.d/su , the su command will only allow users in the
# wheel group to execute su .
# Rationale:
# Restricting the use of su , and using sudo in its place, provides system administrators better
# control of the escalation of user privileges to execute privileged commands. The sudo utility
# also provides a better logging and audit mechanism, as it can log each command executed
# via sudo , whereas su can only record that a user executed the su program.

test=$1

# check for Augtool
type augtool &> /dev/null

if [[ $? == 1 ]]
then
    echo -e "\n>>> Augtool binary not installed on this host, skipping this rule..."
    exit 1
fi

ret=$(augtool print "/files/etc/pam.d/su/*[module='pam_wheel.so'][type='auth'][control='required']/argument[ . = 'use_uid']")
if [[ -z "${ret}" ]]
then
    echo -e "\n>>> 'auth required pam_wheel.so use_uid' in not set in /etc/pam.d/su"

    # Remediate
    if [[ -z $test ]]
    then
        echo -e "\n>>> Setting 'auth required pam_wheel.so use_uid' in /etc/pam.d/su"
        augtool set "/files/etc/pam.d/su/*[module='pam_wheel.so'][type='auth'][control='required']/argument[ . = 'use_uid'] use_uid"
    fi
fi
