#!/bin/bash
# 6.2.13 Ensure users' .netrc Files are not group or world accessible

# While the system administrator can establish secure permissions for users' .netrc files, the
# users can easily override these.
# Rationale:
# .netrc files may contain unencrypted passwords that may be used to attack other systems.

cat /etc/passwd | egrep -v '^(root|halt|sync|shutdown|adm|bin|daemon)' | awk -F: '($7 !="/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; 
do
    if [ ! -d "$dir" ]; then
        echo -e "\n>>> The home directory ($dir) of user $user does not exist."
    else
        for file in $dir/.netrc; do
            if [ ! -h "$file" -a -f "$file" ]; then
                
                fileperm=$(ls -ld $file | cut -f1 -d" ")
                
                if [ $(echo $fileperm | cut -c5) != "-" ]; then
                    echo -e "\n>>> Group Read set on $file"
                fi
                
                if [ $(echo $fileperm | cut -c6) != "-" ]; then
                    echo -e "\n>>> Group Write set on $file"
                fi
                
                if [ $(echo $fileperm | cut -c7) != "-" ]; then
                    echo -e "\n>>> Group Execute set on $file"
                fi
                
                if [ $(echo $fileperm | cut -c8) != "-" ]; then
                    echo -e "\n>>> Other Read set on $file"
                fi
                
                if [ $(echo $fileperm | cut -c9) != "-" ]; then
                    echo -e "\n>>> Other Write set on $file"
                fi

                if [ $(echo $fileperm | cut -c10) != "-" ]; then
                    echo -e "\n>>> Other Execute set on $file"
                fi
            fi
        done
    fi
done