#!/bin/bash

# 6.2.10 Ensure users' dot files are not group or world writable
# Description:
# While the system administrator can establish secure permissions for users' "dot" files, the
# users can easily override these.
# Rationale:
# Group or world-writable user configuration files may enable malicious users to steal or
# modify other users' data or to gain another user's system privileges.

cat /etc/passwd | egrep -v '^(root|halt|sync|shutdown|bin|adm|daemon)' | awk -F: '($7 !="/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; 
do
    if [ ! -d "$dir" ]; then
        echo -e "\n>>> The home directory ($dir) of user $user does not exist."
    else
        for file in $dir/.[A-Za-z0-9]*; do
            if [ ! -h "$file" -a -f "$file" ]; 
            then
                fileperm=$(ls -ld $file | cut -f1 -d" ")
                
                if [ $(echo $fileperm | cut -c6) != "-" ]; 
                then
                    echo -e "\n>>> Group Write permission set on file $file"
                fi
                
                if [ $(echo $fileperm | cut -c9) != "-" ];
                then
                    echo -e "\n>>> Other Write permission set on file $file"
                fi
            fi
        done
    fi
done