#!/bin/bash

# 6.2.8 Ensure users' home directories permissions are 750 or more restrictive
# Description:
# While the system administrator can establish secure permissions for users' home
# directories, the users can easily override these.
# Rationale:
# Group or world-writable user home directories may enable malicious users to steal or
# modify other users' data or to gain another user's system privileges.

cat /etc/passwd | egrep -v '^(halt|sync|shutdown|bin|daemon|adm)' | awk -F: '($7 !="/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; do
    if [ ! -d "$dir" ]; then
        echo -e "\n>>> The home directory ($dir) of user $user does not exist."
    else
        dirperm=$(ls -ld $dir | cut -f1 -d" ")
    
        if [ $(echo $dirperm | cut -c6) != "-" ]; then
            echo -e "\n>>> Group Write permission set on the home directory ($dir) of user $user"
        fi

        if [ $(echo $dirperm | cut -c8) != "-" ]; then
            echo -e "\n>>> Other Read permission set on the home directory ($dir) of user $user"
        fi

        if [ $(echo $dirperm | cut -c9) != "-" ]; then
            echo -e "\n>>> Other Write permission set on the home directory ($dir) of user $user"
        fi

        if [ $(echo $dirperm | cut -c10) != "-" ]; then
            echo -e "\n>>> Other Execute permission set on the home directory ($dir) of user $user"
        fi
    fi
done