#!/bin/bash

# 6.2.17 Ensure no duplicate GIDs exist
# 
# Description:
# Although the groupadd program will not let you create a duplicate Group ID (GID), it is
# possible for an administrator to manually edit the /etc/group file and change the GID field.
# Rationale:
# User groups must be assigned unique GIDs for accountability and to ensure appropriate
# access protections.

cat /etc/group | cut -f3 -d":" | sort -n | uniq -c | while read x ; do
    [ -z "${x}" ] && break
    set - $x
    
    if [ $1 -gt 1 ]; then
        groups=$(awk -F: '($3 == n) { print $1 }' n=$2 /etc/group | xargs)
        echo -e "\n>>> Duplicate GID ($2): ${groups}"
    fi
done