#!/bin/bash

# 6.2.7 Ensure all users' home directories exist

# Description:
# Users can be defined in /etc/passwd without a home directory or with a home directory
# that does not actually exist.

# Rationale:
# If the user's home directory does not exist or is unassigned, the user will be placed in "/"
# and will not be able to write any files or have local environment variables set.

cat /etc/passwd | egrep -v '^(root|halt|sync|shutdown)' | awk -F: '($7 !="/sbin/nologin" && $7 != "/bin/false") { print $1 " " $6 }' | while read user dir; do

if [ ! -d "$dir" ]; then
    echo -e "\n>>> $dir"
fi
done